### PR TITLE
Japanese doc has been created.

### PR DESCRIPTION
**Pull request by reindex-ot**
I made it.
kurukuru~

### CODE REVIEW

**Comment by Scighost** [comment]
Thanks for your contributions. However, there are some problems:

- The original `Configuration.md` has been deleted
- No links to Japanese on the first line of each document

**Comment by reindex-ot** [comment]
fix & update...

**Comment by Scighost** [comment]
I noticed you pushed a lot of times, could I merge it?

**Comment by reindex-ot** [comment]
ok, let's go.

**Comment by Scighost** [comment]
image

**Pull request merged**
