### PR TITLE
Fix Crowdin badge error

### PR DESCRIPTION
**Pull request by phucho0237**

### CODE REVIEW

**Comment by Scighost** [comment]
Thanks for your pull request, but I want it always displays 100% progress of en-us translation. Do you have some way to achieve it?

**Comment by phucho0237** [comment]
You mean like:

[en_US translation](https://crowdin.com/project/starward)

**Comment by Scighost** [comment]
Yes, that's good!

**Comment by phucho0237** [comment]
Done @Scighost

**Pull request merged**
